people:
  - name: Sammie
    timezone: Asia/Shanghai
    available:
      - begin: 01-01 00:00
        end: 01-02 00:00
        weight: 1
      - begin: 01-02 08:00
        end: 01-02 16:00
        weight: 4
      - begin: 01-05 16:00
        end: 01-05 20:00
        weight: 3
  - name: Mike
    timezone: Europe/Paris
    available:
      - begin: 01-01 19:00
        end: 01-01 20:30
        weight: 1
      - begin: 01-02 00:00
        end: 01-02 23:00
        weight: 2
      - begin: 01-03 08:00
        end: 01-06 00:00
        weight: 4
